-- =========================================================================
-- Supabase Setup Script for ShareFlow
-- =========================================================================
-- Paste this script into the Supabase SQL Editor to set up your tables.

-- 1. Create the shared_links metadata table
create table if not exists public.shared_links (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    secret_id text not null unique,
    file_name text not null,
    file_size bigint not null,
    storage_path text not null,
    password text,               -- Optional password security
    expiry_days integer default 7 -- Optional expiration timeframe
);

-- Enable Row Level Security (RLS) on shared_links
alter table public.shared_links enable row level security;

-- Create policies to allow public anonymous read and write access
create policy "Allow public read access" 
on public.shared_links for select 
using (true);

create policy "Allow public insert access" 
on public.shared_links for insert 
with check (true);

-- 2. Create the storage bucket named 'user_files'
-- Note: You can create the bucket manually via the Supabase Storage Dashboard:
--   - Go to Storage > Buckets > New Bucket
--   - Set Name to: user_files
--   - Set the bucket to PUBLIC or write bucket policies.
-- Alternatively, if you have permissions, you can run this script to initialize it:

insert into storage.buckets (id, name, public) 
values ('user_files', 'user_files', true)
on conflict (id) do nothing;

-- Create Storage Policies to allow public read/write inside 'user_files'
create policy "Allow public bucket read"
on storage.objects for select
using ( bucket_id = 'user_files' );

create policy "Allow public bucket insert"
on storage.objects for insert
with check ( bucket_id = 'user_files' );
